name = "TALENDRO/talendro"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'TALENDRO/talendro'"

[repository]
user = "TALENDRO"
project = "talendro"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.8"
source = "github"

[[dependencies]]
name = "aiken-extra/tx_util"
version = "2.220.202412"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config]
